language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  
install:
  - "sudo apt-get install -y scons"
  - "sudo python setup.py install"

script:
  - python tests/test_gs.py
